import { InMemoryDBEntity } from '@nestjs-addons/in-memory-db';

export interface LedgerEntity extends InMemoryDBEntity {
  createdAt: number;
  title: string;
  mode: 'INCOME' | 'EXPENSE';
  amountInCents: number;
  categoryId: string | null;
}
export const initialLedgers: LedgerEntity[] = [
  {
    createdAt: new Date(2022, 0, 1, 7, 10).valueOf(),
    categoryId: '1',
    id: '1',
    title: 'Wynajem',
    mode: 'EXPENSE',
    amountInCents: 75000,
  },
  {
    id: '2',
    categoryId: '2',
    title: 'Przejazd pociągiem',
    mode: 'EXPENSE',
    amountInCents: 2000,
    createdAt: new Date(2022, 0, 1, 7, 12).valueOf(),
  },
  {
    id: '3',
    categoryId: '2',
    title: 'Przejazd pociągiem',
    mode: 'EXPENSE',
    amountInCents: 8500,
    createdAt: new Date(2022, 0, 1, 7, 15).valueOf(),
  },
  {
    id: '4',
    categoryId: '3',
    createdAt: new Date(2022, 0, 1, 7, 20).valueOf(),
    title: 'Restaurcja - gatto matto',
    mode: 'EXPENSE',
    amountInCents: 4500,
  },
  {
    id: '5',
    categoryId: '3',
    createdAt: new Date(2022, 0, 1, 7, 25).valueOf(),
    title: 'Pizza',
    mode: 'EXPENSE',
    amountInCents: 3000,
  },
  {
    id: '6',
    categoryId: '3',
    createdAt: new Date(2022, 0, 1, 7, 30).valueOf(),
    title: 'Restauracja - Mamma Mia!',
    mode: 'EXPENSE',
    amountInCents: 8000,
  },
  {
    id: '7',
    categoryId: '4',
    createdAt: new Date(2022, 0, 1, 7, 35).valueOf(),
    title: 'Gaz',
    mode: 'EXPENSE',
    amountInCents: 3600,
  },
  {
    id: '8',
    categoryId: '4',
    createdAt: new Date(2022, 0, 1, 7, 40).valueOf(),
    title: 'Energia',
    mode: 'EXPENSE',
    amountInCents: 16700,
  },
  {
    id: '9',
    categoryId: '4',
    createdAt: new Date(2022, 0, 1, 7, 45).valueOf(),
    title: 'Usługi komunalne',
    mode: 'EXPENSE',
    amountInCents: 5000,
  },
  {
    id: '10',
    categoryId: '5',
    createdAt: new Date(2022, 0, 1, 7, 46).valueOf(),
    title: 'Ubezpieczene na życie - składka',
    mode: 'EXPENSE',
    amountInCents: 3000,
  },
  {
    id: '11',
    categoryId: '6',
    createdAt: new Date(2022, 0, 1, 7, 48).valueOf(),
    title: 'Składka na poduszkę finansową',
    mode: 'EXPENSE',
    amountInCents: 100000,
  },
  {
    id: '12',
    categoryId: '6',
    createdAt: new Date(2022, 0, 1, 7, 50).valueOf(),
    title: 'Zakup WIG20',
    mode: 'EXPENSE',
    amountInCents: 50000,
  },
  {
    id: '13',
    categoryId: '7',
    createdAt: new Date(2022, 0, 1, 7, 55).valueOf(),
    title: 'Bilety do kina',
    mode: 'EXPENSE',
    amountInCents: 3200,
  },
  {
    id: '14',
    categoryId: '7',
    createdAt: new Date(2022, 0, 1, 8, 10).valueOf(),
    title: 'Fryzjer',
    mode: 'EXPENSE',
    amountInCents: 12000,
  },
  {
    id: '15',
    categoryId: '8',
    createdAt: new Date(2022, 0, 1, 8, 20).valueOf(),
    title: 'Chemia do kuchni',
    mode: 'EXPENSE',
    amountInCents: 2800,
  },
  {
    id: '16',
    categoryId: '8',
    createdAt: new Date(2022, 0, 1, 8, 25).valueOf(),
    title: 'Waga łazienkowa',
    mode: 'EXPENSE',
    amountInCents: 8999,
  },
  {
    id: '17',
    categoryId: null,
    createdAt: new Date(2022, 0, 1, 8, 30).valueOf(),
    title: 'Wypłata',
    mode: 'INCOME',
    amountInCents: 1200000,
  },
];
